### ISSUE TITLE
Dolibarr v7.0.3 Testing

### ISSUE THREAD

**Issue by aljawaid** [caos30/dolibarr_stocktransfers_module#3]
Hello, some feedback for the testing on DB 7.0.3... 

![image](https://user-images.githubusercontent.com/10233708/43555330-72c10f64-95f1-11e8-85e0-26fa03dfd617.png)

**Comment by caos30** [comment]
Ok, in this last upgrade to v 1.5 i fixed these issues you found. And i improved some other little issues on the same view. Your suggestions were very profitable, so i must thanks to you!! Cheers.

**Comment by aljawaid** [comment]
![image](https://user-images.githubusercontent.com/10233708/44617045-f7538d00-a853-11e8-8d19-211929b1d494.png)

After v1.5, the above picture is my further suggestions.

**Comment by caos30** [comment]
1. The user who add a new sotck transfer can set its "label". If he leaves it empty then the module build an automatic label using the prefix "Transfer Stock" (i think that maybe it could be only TS) and the date in a "alphabetically sortable format" so: year-month-day-hour-minute. I can understand that the this format is no usually used to show dates, but the idea is not to show dates, but to generate UNIQUE text labels implementing a "timestamp" with "some of sense". For this reason and to get a shorter automatic label i realize now that maybe it's better idea to put "TS" as prefix instead of "Transfer stock". But the date... ummm... i'm not very sure that the BEST format would be the localized format.

2. Question: all the users on a Dolibarr instance, has access to "module settings"? Because my reason to put the access to User Guide on the bottom page of the list view was precisely to be accesible the HELP to each user although she is not an admin. Please answer my question please. Furthermore, maybe you see "rare" to appear the module version number beside the "User Guide", but i choosed to do it just to not leav ALONE tha tlink. I think that it's not annoying. In fact, as you can see, i used a hrey font color to not get very much attention.

3. I cannot understand hos it's possible that the REFERENCE NAME of your WAREHOUSE is not visible on this transfer list !? in my Dolibarr it appears:
![seleccio_378](https://user-images.githubusercontent.com/1767547/44621915-ae0b3980-a863-11e8-82c1-242064b0fd20.png)
The module is taking the value of the REF. field in the warehouse profile:
![seleccio_379](https://user-images.githubusercontent.com/1767547/44622020-55d53700-a865-11e8-8c21-8a3eeab328e9.png)
Could it be a proble of Dolibarr version? I'm using just now for this changes v5.0.4 and i'm quite sure that it run fine for Dolibar 6. Are you testing this on Dolibarr 7?

4. Regarding the hover effect, i've not problem, please see this animated GIF to look how it appears on my browser. 
![peek 2018-08-25 12-44](https://user-images.githubusercontent.com/1767547/44621972-aac47d80-a864-11e8-8b83-e9803ef85a95.gif)
Can you show me how it looks on your browser?

**Comment by caos30** [comment]
Oh, sorry, after send my last comment i just realize that your comments are just about DOLIBARR VERSION 7 !!!

Title of this issue: "Dolibarr v7.0.3 Testing"

Sorry, this could then explain some of the issues you reported. The bad news is that i need to install Doli 7 on my machine before to be able to test&fix the issues. So, i will need more time.

**Comment by aljawaid** [comment]
1. I didn't know we could customize the label.  That's good, but the date hmmmm... I still think it would be better in local format as the whole of dolibarr is showing dates in local format so will be consistent for the end users.
2. I'm not sure but maybe if it was at the bottom of the browser screen instead of the bottom of the page (which is half the screen if only one entry in the list) then it may make more sense.  Another idea, would be to add an option in the module settings to show or hide the link.
3. Yes, testing on v7.0.3
4. I don't know how to create a gif like that to show you lol
but in `stocktransfer.php.css` I tested with the below code and it removed the clunky hover effect:
```/* new transfer button hover fix */
.button {
display: unset !important;
}```

**Comment by caos30** [comment]
4. to do cool GIF animations recording your mousework on your screen, i use Peek, but i don't know if it runs on Windows or Mac (what OS do you use on your desktop?). Anyway, there are similar software to do the same in all OSs 

> [https://github.com/phw/peek](https://github.com/phw/peek)

Said this, please try to make a little screencast like mine to share here about this hover effect, if you want help on it.

Indeed, i think that this hover effect is not responsability of the stocktransfers module, but the dolibarr theme you have installed. It's true that i modified my dolibarr theme (the one you see on my screenshots), but it has none relation with the stocktransfers module.

**Comment by aljawaid** [comment]
Hello, any update?

**Comment by caos30** [comment]
Hello @aljawaid, i finally uploaded a 1.7 version fixing and implementing your suggestions on this issue. Also, coming soon (this week) i will add a new settings form to be let user of Dolibarr instance to customize some behaviours of the module.

This is possible thanks to a customer of mine (@marcovalerioed,) who paid for interesting customization settings specially for the PDF built by module.

**Comment by caos30** [comment]
By the way, @aljawaid, this new version of the module is compatible with the last Dolibarr versions (5-9.0.x). I mention this, if you continue interested on use the module ;-)

Cheers!
Sergi
